### ISSUE TITLE
PRIP API: Response serialization fails for format XML

### ISSUE THREAD

**Issue by tangobravo62** [dlr-eoc/prosEO#122]
When requesting a product catalogue in XML format, the request fails with an exception:
```
2020-10-28 11:20:48.721 ERROR 1 --- [nio-8080-exec-1] p.a.p.o.ProductEntityCollectionProcessor : (E5007) Request failed (cause java.lang.NullPointerException: null)
java.lang.NullPointerException
	at java.xml/com.sun.xml.internal.stream.writers.XMLStreamWriterImpl.writeXMLContent(XMLStreamWriterImpl.java:1486)
	at java.xml/com.sun.xml.internal.stream.writers.XMLStreamWriterImpl.writeAttribute(XMLStreamWriterImpl.java:553)
	at org.apache.olingo.server.core.serializer.xml.ODataXmlSerializer.writeEntity(ODataXmlSerializer.java:493)
	at org.apache.olingo.server.core.serializer.xml.ODataXmlSerializer.writeEntitySet(ODataXmlSerializer.java:414)
	at org.apache.olingo.server.core.serializer.xml.ODataXmlSerializer.entityCollection(ODataXmlSerializer.java:264)
	at de.dlr.proseo.api.prip.odata.ProductEntityCollectionProcessor.readEntityCollection(ProductEntityCollectionProcessor.java:499)
	at org.apache.olingo.server.core.ODataDispatcher.handleEntityCollectionDispatching(ODataDispatcher.java:529)
	at org.apache.olingo.server.core.ODataDispatcher.handleEntityDispatching(ODataDispatcher.java:511)
	at org.apache.olingo.server.core.ODataDispatcher.handleResourceDispatching(ODataDispatcher.java:152)
	at org.apache.olingo.server.core.ODataDispatcher.dispatch(ODataDispatcher.java:118)
	at org.apache.olingo.server.core.ODataHandlerImpl.processInternal(ODataHandlerImpl.java:164)
	at org.apache.olingo.server.core.ODataHandlerImpl.process(ODataHandlerImpl.java:85)
	at org.apache.olingo.server.core.ODataHttpHandlerImpl.process(ODataHttpHandlerImpl.java:74)
	at org.apache.olingo.server.core.ODataHttpHandlerImpl.process(ODataHttpHandlerImpl.java:88)
	at de.dlr.proseo.api.prip.rest.ProductQueryController.service(ProductQueryController.java:104)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
The request was called with the URI:
```
.../proseo/prip/odata/v1/Products?$expand=Attributes&$format=xml
```

**Comment by tangobravo62** [comment]
TODO: Catch the format request and reject the request, if XML is requested.
